### PR TITLE
Bug/differentiate guild handlers

### LINKED ISSUE #49: Slash command handlers do not differentiate between guild and global slash commands
**Describe the bug**
When registering two commands with the same name (by having the commands be different guild commands / one a guild command and the other a global command), the same handler is registered for both commands even if they declare a different handler.

**To Reproduce**
1. Create two commands with the same name and register them to different guilds. Assign a different handler to each one.
2. Execute each command in its own guild. Both commands will trigger the same handler, despite being registered with different handlers.

**Expected behavior**
Each command should have its own handler regardless of name.

**Desktop (please complete the following information):**
 - OS: Linux 5.18.0-artix1-1
 - Dart version: 2.18.0-149.0.dev
 - Nyxx version: 3.4.2
 - nyxx_interactions version: 4.2.1

**Additional context**
This issue is due to command hashes not including guild information.

### PR DESCRIPTION
**Pull request by abitofevrything**
# Description

Closes #49 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [x] Ran `dart analyze` or `make analyze` and fixed all issues
- [x] Ran `dart format --set-exit-if-changed -l 160 ./lib` or `make format` and fixed all issues
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked my changes haven't lowered code coverage

### CODE REVIEW

**Review by l7ssha — DISMISSED** [review]

File: lib/src/models/slash_command_permission.dart [hunk 1]
```diff
@@ -59,17 +59,29 @@ class SlashCommandPermissionOverride implements ISlashCommandPermissionOverride
 abstract class ISlashCommandPermissionOverrides implements SnowflakeEntity {
   /// The permissions attached to the command.
   List<SlashCommandPermissionOverride> get permissionOverrides;
+
+  /// Whether these overrideas are global across all commands in a guild.
```
Comment (Rapougnac) [inline lib/src/models/slash_command_permission.dart:63]:
```suggestion
  /// Whether these overrides are global across all commands in a guild.
```

**Review by Rapougnac — CHANGES_REQUESTED** [review]
Smol typo

**Review by l7ssha — APPROVED** [review]
